version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: rhhcc
    environment:
      POSTGRES_USER: rhhcc
      POSTGRES_PASSWORD: 32167
      POSTGRES_DB: rhhcc
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin_rhhcc_password
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data:
